DROP TABLE PROJECT;
DROP TABLE DEPARTMENT;

CREATE TABLE DEPARTMENT(ID INTEGER NOT NULL, NAME VARCHAR(255), PRIMARY KEY(ID));
CREATE TABLE PROJECT (DEPT_ID INTEGER NOT NULL, NAME VARCHAR(255) NOT NULL, 
                      START_DATE DATE, END_DATE DATE, PRIMARY KEY(DEPT_ID,NAME),
                      CONSTRAINT DEPT_FK FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(ID));

INSERT INTO DEPARTMENT(ID, NAME) VALUES (1, 'Engineering');
INSERT INTO PROJECT (DEPT_ID, NAME, START_DATE, END_DATE) VALUES (1, 'Release3', {d '2002-12-05'}, {d '2002-08-06'});
