DROP TABLE EMP_PRJ;
DROP TABLE EMP;
DROP TABLE EMP_ADDRESS;
DROP TABLE DEPARTMENT;
DROP TABLE ID_GEN;
DROP TABLE PARKINGSPACE;
DROP TABLE PROJECT;

CREATE TABLE PROJECT (ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
                         NAME VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE DEPARTMENT (ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
                            NAME VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE PARKINGSPACE (ID INTEGER  NOT NULL, LOT INTEGER, LOCATION VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE EMP (ID INTEGER NOT NULL, NAME VARCHAR(255), STARTDATE DATE,
                     HOURLYRATE FLOAT, SALARY BIGINT, PENSION BIGINT, TYPE VARCHAR(32),
                     STREET VARCHAR(255), CITY VARCHAR(255), PROV VARCHAR(255), PCODE VARCHAR(255),  
                     MGR INTEGER, DEPARTMENT_ID INTEGER, 
                     CONSTRAINT MGR_FK FOREIGN KEY (MGR) REFERENCES EMP(ID),
                     CONSTRAINT DEPARTMENT_FK FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID),
                     PRIMARY KEY (ID));
CREATE TABLE EMP_ADDRESS (EMP_ID INTEGER NOT NULL, STREET VARCHAR(255), 
                  CITY VARCHAR(255), PROV VARCHAR(255), PCODE VARCHAR(255), PRIMARY KEY (EMP_ID));
CREATE TABLE EMP_PRJ(PROJ_ID INTEGER NOT NULL, EMP_ID INTEGER NOT NULL,
                        CONSTRAINT PROJECTS_FK FOREIGN KEY (PROJ_ID) REFERENCES PROJECT (ID),
                        CONSTRAINT EMPLOYEES_FK FOREIGN KEY (EMP_ID) REFERENCES EMP (ID),
                        PRIMARY KEY (PROJ_ID, EMP_ID));
CREATE TABLE ID_GEN (GEN_NAME VARCHAR(80), GEN_VAL INTEGER, PRIMARY KEY (GEN_NAME));


INSERT INTO ID_GEN (GEN_NAME, GEN_VAL) VALUES ('Emp_Gen', 10);

INSERT INTO PARKINGSPACE (ID, LOT, LOCATION) VALUES (1, 1, 'East Lot');
INSERT INTO PARKINGSPACE (ID, LOT, LOCATION) VALUES (2, 2, 'West Lot');
INSERT INTO PARKINGSPACE (ID, LOT, LOCATION) VALUES (5, 3, 'North Lot');
INSERT INTO PARKINGSPACE (ID, LOT, LOCATION) VALUES (6, 4, 'South Lot');

INSERT INTO DEPARTMENT (NAME) VALUES ('Engineering');
INSERT INTO DEPARTMENT (NAME) VALUES ('QA');
INSERT INTO DEPARTMENT (NAME) VALUES ('Accounting');

INSERT INTO PROJECT (NAME) VALUES ('Design Release2');
INSERT INTO PROJECT (NAME) VALUES ('Release1');
INSERT INTO PROJECT (NAME) VALUES ('Test Release2');

INSERT INTO EMP (ID, NAME, STARTDATE, HOURLYRATE, PENSION, SALARY, TYPE, MGR, DEPARTMENT_ID) 
         VALUES (1, 'Patrick', {d '2004-07-01'}, NULL, 55000, 100000, 'FT', NULL, 1);
INSERT INTO EMP_ADDRESS (EMP_ID, CITY, PROV, STREET, PCODE)
         VALUES (1, 'New York', 'NY', '123 Apple Tree Cr.', '10001');
INSERT INTO EMP (ID, NAME, STARTDATE, HOURLYRATE, PENSION, SALARY, TYPE, MGR, DEPARTMENT_ID) 
         VALUES (2, 'Joan', {d '2003-09-09'}, NULL, 59000, 200000, 'FT', 1, 2);
INSERT INTO EMP_ADDRESS (EMP_ID, CITY, PROV, STREET, PCODE)
         VALUES (2, 'Manhattan', 'NY', '654 Stanton Way.', '10003');
INSERT INTO EMP (ID, NAME, STARTDATE, HOURLYRATE, PENSION, SALARY, TYPE, MGR, DEPARTMENT_ID) 
         VALUES (3, 'Samantha', {d '2000-03-12'}, NULL, 60000, 450000, 'FT', 1, 3);
INSERT INTO EMP_ADDRESS (EMP_ID, CITY, PROV, STREET, PCODE)
         VALUES (3, 'New York', 'NY', '99 Queen St.', '10001');
INSERT INTO EMP (ID, NAME, STARTDATE, HOURLYRATE, PENSION, SALARY, TYPE, MGR, DEPARTMENT_ID) 
         VALUES (4, 'Samantha', {d '2000-03-12'}, NULL, 60000, 450000, 'FT', 1, 1);
INSERT INTO EMP_ADDRESS (EMP_ID, CITY, PROV, STREET, PCODE)
         VALUES (4, 'Redwood Shores', 'CA', '445 McDonell Cr.', '10001');

INSERT INTO EMP (ID, NAME, STARTDATE, HOURLYRATE, PENSION, SALARY, TYPE, MGR, DEPARTMENT_ID) 
         VALUES (5, 'Mark', {d '2004-11-01'}, 17.0, NULL, NULL, 'PT', NULL, 2);
INSERT INTO EMP_ADDRESS (EMP_ID, CITY, PROV, STREET, PCODE)
         VALUES (5, 'San Jose', 'CA', '624 Hamilton Dr.', '90123');
INSERT INTO EMP (ID, NAME, STARTDATE, HOURLYRATE, PENSION, SALARY, TYPE, MGR, DEPARTMENT_ID) 
         VALUES (6, 'Ryan', {d '2005-12-05'}, 16.0, NULL, NULL, 'PT', 5, 3);
INSERT INTO EMP_ADDRESS (EMP_ID, CITY, PROV, STREET, PCODE)
         VALUES (6, 'San Jose', 'CA', '724 Coventry Rd.', '90123');
INSERT INTO EMP (ID, NAME, STARTDATE, HOURLYRATE, PENSION, SALARY, TYPE, MGR, DEPARTMENT_ID) 
         VALUES (7, 'Jackie', {d '2006-01-03'}, 15.0, NULL, NULL, 'PT', 5, 1);
INSERT INTO EMP_ADDRESS (EMP_ID, CITY, PROV, STREET, PCODE)
         VALUES (7, 'San Francisco', 'CA', '77 Manchester Blvd.', '90123');
INSERT INTO EMP (ID, NAME, STARTDATE, HOURLYRATE, PENSION, SALARY, TYPE, MGR, DEPARTMENT_ID) 
         VALUES (8, 'Jackie', {d '2006-01-03'}, 15.0, NULL, NULL, 'PT', 5, 2);
INSERT INTO EMP_ADDRESS (EMP_ID, CITY, PROV, STREET, PCODE)
         VALUES (8, 'San Jose', 'CA', '624 High Tech Ave.', '90123');

INSERT INTO EMP_PRJ (PROJ_ID, EMP_ID) VALUES (1, 1);

